language: php

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer install --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-text
  - ./vendor/bin/phpcs
