language: php

sudo: false

notifications:
  email:
    on_success: never
    on_failure: always

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer install --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-text
  - ./vendor/bin/phpcs
